name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  weather-ml-app:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'
        
    - name: Install Dependencies
      run: |
        python3 -m venv flaskappenv  
        source flaskappenv/bin/activate
        pip install -r requirements.txt
        pip install Flask gunicorn

    - name: Run integration test
      run: |
        source flaskappenv/bin/activate
        python3 -m unittest tests/integration_test.py

    - name: Run smoke test
      run: |
        source flaskappenv/bin/activate
        python3 -m unittest tests/smoke_test.py 

    - name: Run unit test
      run: |
        source flaskappenv/bin/activate
        python3 -m unittest tests/integration_test.py
    
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


      
